server:
  port: 8080

spring:
  application:
    name: word-king-backend
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  h2:
    console:
      enabled: true

mybatis-plus:
  type-aliases-package: com.wordking.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_

logging:
  config: classpath:logback-spring.xml

# 自定义配置
word-king:
  upload:
    path: /uploads/